@startuml

actor Manger as "Department Manager"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Get salaries
    for deparment manger department"

    usecase UCa as "Print salaries"

    Manger - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml