@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Get employee by emp_no"

    usecase UCa as "Update Info"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml